/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package classes;

import java.awt.Font;



/**
 *
 * @author Karen Campinas
 */
public class TelaThinknator extends javax.swing.JFrame {

    /**
     * Creates new form telaThinknator
     */
    public TelaThinknator() { /* Método CONSTRUTOR = A ideia do construtor é 
        executar assim que a tela aparecer. */
        initComponents();
        lblFrase.setText("<html>Vou pensar em um valor entre <strong>1 e 10</strong>, tente adivinhar...</html>")/* O Java é totalmente 
        compatível com a linguagem de marcação HTML, o simples fato de colocar a frase entre a tag <html></html> 
        já nos garante a quebra de linha*/;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblFrase = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JSpinner();
        btnPalpite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 153));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setLocation(new java.awt.Point(450, 180));
        setMaximumSize(new java.awt.Dimension(412, 400));
        setMinimumSize(new java.awt.Dimension(412, 400));
        setPreferredSize(new java.awt.Dimension(412, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/thinknator-peq.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        lblFrase.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        lblFrase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFrase.setText("Frase");
        getContentPane().add(lblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ballon.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        lblValor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 24)); // NOI18N
        lblValor.setText("Valor");
        getContentPane().add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 70, -1));

        txtValor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 16)); // NOI18N
        txtValor.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 50, 30));

        btnPalpite.setBackground(new java.awt.Color(51, 0, 153));
        btnPalpite.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 24)); // NOI18N
        btnPalpite.setForeground(new java.awt.Color(255, 255, 255));
        btnPalpite.setText("Palpite");
        btnPalpite.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.MatteBorder(null)));
        btnPalpite.setBorderPainted(false);
        btnPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 120, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
        // TODO add your handling code here:
        /* Nesta parte sorteamos um número */
        double n = 1 /* O início */ + Math.random() * (11 - 1) /* (O número final + 1) - 1 */;
        int valor = (int) n; /* A variável "valor" vai ser a parte inteira de "n" */
        
        /* Aqui pegamos um número que o usuário digitou */
        int num = Integer.parseInt(txtValor.getValue().toString());
        
        /* Aqui vou configurar as frases */
        String f1 = "<html><p style='color: green ; margin-right: 10px'>ACERTOU!</p></html>";
        String f2 = "<html><p style='color: red'>ERROU! Eu pensei no valor " + "<span style='color: rgb(255, 79, 0)'><u>" + valor + "</u></span>.</p></html>";
        
        /* Atribuição das frases à variável "res" */
        String res = (valor == num)?f1:f2;
        
        lblFrase.setFont(new Font("Arial Black", Font.PLAIN, 16)) /* Plain = Normal em HTML */;
        
        lblFrase.setText(res);
        
    }//GEN-LAST:event_btnPalpiteActionPerformed

   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaThinknator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaThinknator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaThinknator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaThinknator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaThinknator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JLabel lblValor;
    private javax.swing.JSpinner txtValor;
    // End of variables declaration//GEN-END:variables
}
